version: "3.8"
services:
  Cards56Hub:
    image: bheemboy/api_56cards
    container_name: api_56cards
    ports:
      - 8080:80
    networks:
      - app_network

  nginx:
    restart: always
    image: nginx:1-alpine
    ports:
      - 80:80
    volumes:
      - ./wwwroot/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - Cards56Hub
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
