services:
  nginx:
    image: nginx
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - .:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
